# Generated by Django 5.1.2 on 2024-12-07 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=20, verbose_name='Status')),
                ('date', models.DateField(verbose_name='Payment Date')),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_number', models.CharField(max_length=20, verbose_name='Transport Number')),
                ('capacity', models.PositiveIntegerField(verbose_name='Capacity')),
                ('available_seats', models.PositiveIntegerField(verbose_name='Available Seats')),
                ('technical_condition', models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Satisfactory', 'Satisfactory'), ('Needs Repair', 'Needs Repair')], default='Good', max_length=20, verbose_name='Technical Condition')),
            ],
        ),
    ]
