# Generated by Django 5.1.2 on 2024-12-07 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_payment_transport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
