# Generated by Django 5.1.2 on 2024-12-07 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_delete_vehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transport',
            name='available_seats',
        ),
    ]
