# Generated by Django 5.1.2 on 2024-12-07 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_remove_transport_available_seats'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transport',
        ),
    ]
