# Generated by Django 5.1.2 on 2024-12-07 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0005_delete_transport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_number', models.CharField(max_length=20, verbose_name='Transport Number')),
                ('capacity', models.PositiveIntegerField(verbose_name='Capacity')),
                ('model', models.CharField(max_length=50, verbose_name='Model')),
                ('technical_condition', models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Satisfactory', 'Satisfactory'), ('Needs Repair', 'Needs Repair')], default='Good', max_length=20, verbose_name='Technical Condition')),
            ],
        ),
    ]
