# Generated by Django 5.1.2 on 2024-12-07 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0006_transport'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadyRouteOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('start_route', models.CharField(max_length=100)),
                ('end_route', models.CharField(max_length=100)),
                ('departure_date', models.DateField()),
                ('seats', models.PositiveIntegerField()),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='transport.route')),
            ],
        ),
    ]
