# Generated by Django 5.1.2 on 2024-12-07 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0008_existingrouteorder_delete_readyrouteorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('departure_date', models.DateField()),
                ('seats', models.PositiveIntegerField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('days_count', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.route')),
            ],
        ),
        migrations.DeleteModel(
            name='ExistingRouteOrder',
        ),
    ]
