# Generated by Django 5.1.2 on 2024-12-07 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0009_routeorder_delete_existingrouteorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RouteOrder',
        ),
    ]
