# Generated by Django 5.1.2 on 2024-12-07 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0011_routebooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routebooking',
            name='days_count',
        ),
        migrations.RemoveField(
            model_name='routebooking',
            name='end_route',
        ),
        migrations.RemoveField(
            model_name='routebooking',
            name='price',
        ),
        migrations.RemoveField(
            model_name='routebooking',
            name='seats',
        ),
        migrations.RemoveField(
            model_name='routebooking',
            name='start_route',
        ),
        migrations.RemoveField(
            model_name='routebooking',
            name='status',
        ),
        migrations.AlterField(
            model_name='routebooking',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='transport.route'),
        ),
    ]
