# Generated by Django 5.1.2 on 2024-12-07 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0012_remove_routebooking_days_count_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RouteBooking',
        ),
    ]
