# Generated by Django 5.1.2 on 2024-12-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0014_routebooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('В обработке', 'В обработке'), ('Одобрено', 'Одобрено'), ('Завершено', 'Завершено'), ('Отказано', 'Отказано')], default='В обработке', max_length=20),
        ),
    ]
