# Generated by Django 5.1.2 on 2024-12-08 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0015_alter_request_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Driver Name')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('license_number', models.CharField(max_length=50, verbose_name='License Number')),
            ],
        ),
    ]
