# Generated by Django 5.1.2 on 2024-12-09 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0016_driver'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='transport.driver')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='transport.request')),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='transport.transport')),
            ],
        ),
    ]
