# Generated by Django 5.1.2 on 2024-12-09 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0017_driverschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverschedule',
            name='departure_date',
            field=models.DateField(default='2024-01-01'),
            preserve_default=False,
        ),
    ]
