# Generated by Django 5.1.2 on 2024-12-10 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0019_remove_driverschedule_departure_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='transport.driver'),
        ),
        migrations.AddField(
            model_name='request',
            name='transport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='transport.transport'),
        ),
        migrations.AddField(
            model_name='routebooking',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_bookings', to='transport.driver'),
        ),
        migrations.AddField(
            model_name='routebooking',
            name='status',
            field=models.CharField(choices=[('В обработке', 'В обработке'), ('Одобрено', 'Одобрено'), ('Завершено', 'Завершено'), ('Отказано', 'Отказано')], default='В обработке', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='routebooking',
            name='transport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_bookings', to='transport.transport'),
        ),
    ]
