# Generated by Django 5.1.2 on 2025-02-07 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0020_request_driver_request_transport_routebooking_driver_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.DateField()),
                ('status', models.CharField(choices=[('В обработке', 'В обработке'), ('Одобрено', 'Одобрено'), ('Завершено', 'Завершено'), ('Отказано', 'Отказано')], default='В обработке', max_length=20, verbose_name='Статус')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='transport.route')),
                ('transport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='transport.transport')),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Driver Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Driver Name')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('license_number', models.CharField(max_length=50, verbose_name='License Number')),
                ('aviable', models.BooleanField(max_length=50, verbose_name='License Number')),
            ],
        ),
        migrations.CreateModel(
            name='Route_custom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_location', models.CharField(max_length=255)),
                ('end_location', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('number_of_days', models.IntegerField(blank=True, null=True)),
                ('seats', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='request',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='driverschedule',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='routebooking',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='driverschedule',
            name='request',
        ),
        migrations.RemoveField(
            model_name='driverschedule',
            name='transport',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.RemoveField(
            model_name='request',
            name='transport',
        ),
        migrations.RemoveField(
            model_name='routebooking',
            name='route',
        ),
        migrations.RemoveField(
            model_name='routebooking',
            name='transport',
        ),
        migrations.AddField(
            model_name='booking',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='transport.clients'),
        ),
        migrations.AddField(
            model_name='booking',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='transport.drivers'),
        ),
        migrations.AddField(
            model_name='booking',
            name='route_custom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='transport.route_custom'),
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
        migrations.DeleteModel(
            name='DriverSchedule',
        ),
        migrations.DeleteModel(
            name='Request',
        ),
        migrations.DeleteModel(
            name='RouteBooking',
        ),
    ]
