# Generated by Django 5.1.2 on 2025-02-08 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0021_booking_clients_drivers_route_custom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='email',
        ),
    ]
