# Generated by Django 5.1.2 on 2025-02-09 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0022_remove_clients_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route_custom',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
