# Generated by Django 5.1.2 on 2025-02-23 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0023_alter_route_custom_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='route',
            options={'verbose_name': 'Маршрут', 'verbose_name_plural': 'Маршруты'},
        ),
    ]
