# Generated by Django 5.1.2 on 2025-02-23 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0024_alter_route_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='clients',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='drivers',
            options={'verbose_name': 'Водитель', 'verbose_name_plural': 'Водители'},
        ),
        migrations.AlterModelOptions(
            name='route_custom',
            options={'verbose_name': 'МаршрутПользователя', 'verbose_name_plural': 'МаршрутыПользователей'},
        ),
        migrations.AlterModelOptions(
            name='transport',
            options={'verbose_name': 'Транспорт', 'verbose_name_plural': 'Транспорты'},
        ),
    ]
