# Generated by Django 5.1.2 on 2025-02-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0025_alter_booking_options_alter_clients_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='end_location',
            field=models.CharField(max_length=255, verbose_name='Конец_маршрута'),
        ),
        migrations.AlterField(
            model_name='route',
            name='number_of_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество_дней'),
        ),
        migrations.AlterField(
            model_name='route',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена_маршрута'),
        ),
        migrations.AlterField(
            model_name='route',
            name='seats',
            field=models.IntegerField(default=0, verbose_name='Количество_пасажиров'),
        ),
        migrations.AlterField(
            model_name='route',
            name='start_location',
            field=models.CharField(max_length=255, verbose_name='Начало_маршрута'),
        ),
    ]
