# Generated by Django 5.1.2 on 2025-02-23 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0027_alter_booking_client_alter_booking_driver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='transport.drivers', verbose_name='id водителя'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='transport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='transport.transport', verbose_name='id транспорта'),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='aviable',
            field=models.BooleanField(max_length=50, verbose_name='Доступность'),
        ),
    ]
