# Generated by Django 5.1.2 on 2025-05-03 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0028_alter_booking_driver_alter_booking_transport_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Имя клиента'),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='license_number',
            field=models.CharField(max_length=50, verbose_name='Лицензионный номер'),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='route_custom',
            name='number_of_days',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Количество_дней'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='technical_condition',
            field=models.CharField(choices=[('Excellent', 'Отличное'), ('Needs Repair', 'Требует ремонта')], default='Good', max_length=20, verbose_name='Техническое состояние'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
