# Generated by Django 5.1.2 on 2025-05-03 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0029_alter_clients_first_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
